USE [ContosoRetailDW]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [partitionOnDate](datetime) AS RANGE LEFT FOR VALUES ()


CREATE PARTITION SCHEME [FactSale] AS PARTITION [partitionOnDate] TO ([PRIMARY])






ALTER TABLE [dbo].[FactSales] DROP CONSTRAINT [PK_FactSales_SalesKey] WITH ( ONLINE = OFF )


ALTER TABLE [dbo].[FactSales] ADD  CONSTRAINT [PK_FactSales_SalesKey] PRIMARY KEY NONCLUSTERED 
(
	[SalesKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF, DATA_COMPRESSION = PAGE) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_FactSale_637979968636982583] ON [dbo].[FactSales]
(
	[DateKey]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, DATA_COMPRESSION = PAGE ON PARTITIONS (1)) ON [FactSale]([DateKey])


DROP INDEX [ClusteredIndex_on_FactSale_637979968636982583] ON [dbo].[FactSales]








COMMIT TRANSACTION


